name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # runs whenever code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "✅ All tests passed (no tests defined yet)"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy placeholder
        run: |
          echo "🚀 Deployment step - will configure cloud in Step 4"
